// <auto-generated />
using System;
using InspectionPipeline.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InspectionPipeline.Core.Data.Migrations
{
    [DbContext(typeof(InspectionDbContext))]
    partial class InspectionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("InspectionPipeline.Core.Models.DefectDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BboxH")
                        .HasPrecision(18, 3)
                        .HasColumnType("REAL");

                    b.Property<double>("BboxW")
                        .HasPrecision(18, 3)
                        .HasColumnType("REAL");

                    b.Property<double>("BboxX")
                        .HasPrecision(18, 3)
                        .HasColumnType("REAL");

                    b.Property<double>("BboxY")
                        .HasPrecision(18, 3)
                        .HasColumnType("REAL");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasPrecision(18, 6)
                        .HasColumnType("REAL");

                    b.Property<int>("InspectionRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaskArea")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassName")
                        .HasDatabaseName("IX_DefectDetails_ClassName");

                    b.HasIndex("InspectionRecordId")
                        .HasDatabaseName("IX_DefectDetails_InspectionRecordId");

                    b.ToTable("DefectDetails");
                });

            modelBuilder.Entity("InspectionPipeline.Core.Models.InspectionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AnomalyScore")
                        .HasPrecision(18, 6)
                        .HasColumnType("REAL");

                    b.Property<string>("FinalResult")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("InferenceTimeMs")
                        .HasPrecision(18, 3)
                        .HasColumnType("REAL");

                    b.Property<int>("ModelVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageUsed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FinalResult")
                        .HasDatabaseName("IX_InspectionRecords_FinalResult");

                    b.HasIndex("ModelVersionId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_InspectionRecords_Timestamp");

                    b.HasIndex("Timestamp", "FinalResult")
                        .HasDatabaseName("IX_InspectionRecords_Timestamp_FinalResult");

                    b.ToTable("InspectionRecords");
                });

            modelBuilder.Entity("InspectionPipeline.Core.Models.ModelVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelName")
                        .HasDatabaseName("IX_ModelVersions_ModelName");

                    b.HasIndex("ModelName", "Version")
                        .IsUnique()
                        .HasDatabaseName("IX_ModelVersions_ModelName_Version_Unique");

                    b.ToTable("ModelVersions");
                });

            modelBuilder.Entity("InspectionPipeline.Core.Models.DefectDetail", b =>
                {
                    b.HasOne("InspectionPipeline.Core.Models.InspectionRecord", "InspectionRecord")
                        .WithMany("DefectDetails")
                        .HasForeignKey("InspectionRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InspectionRecord");
                });

            modelBuilder.Entity("InspectionPipeline.Core.Models.InspectionRecord", b =>
                {
                    b.HasOne("InspectionPipeline.Core.Models.ModelVersion", "ModelVersion")
                        .WithMany("InspectionRecords")
                        .HasForeignKey("ModelVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelVersion");
                });

            modelBuilder.Entity("InspectionPipeline.Core.Models.InspectionRecord", b =>
                {
                    b.Navigation("DefectDetails");
                });

            modelBuilder.Entity("InspectionPipeline.Core.Models.ModelVersion", b =>
                {
                    b.Navigation("InspectionRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
